### ISSUE TITLE
Error when starting protege

### ISSUE THREAD

**Issue by magick93** [ABI-Team-30/Fresnel-Forms#78]
Hello

Im trying to get started with Fresnel-Forms. I added the jar to the plugins directory in Protege, however, when starting, it does not load, and in the log is the following:

18:43:05.461 [FelixStartLevel] ERROR FrameworkSlf4jLogger    Error starting file:/home/anton/Documents/software/stanford/Protege-5.0.0-beta-21/plugins/nl.ou.cs.is.protege.plugin.fresnelforms.jar
org.osgi.framework.BundleException: Unresolved constraint in bundle fresnelforms [25]: Unable to resolve 25.0: missing requirement [25.0] osgi.wiring.package; (&(osgi.wiring.package=org.semanticweb.owlapi.model)(version>=3.5.0)(!(version>=4.0.0)))
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2045) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304) [org.apache.felix.main.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
18:43:05.507 [main] INFO  Launcher    The OSGi framework has been started

**Comment by LloydRutledge** [comment]
Try the solution at http://stackoverflow.com/questions/30480508/karaf-maven-unable-to-resolve-missing-requirement-osgi-wiring-package . It looks like not a bug in FForms per se but at aspect of the install context that is needed. Please let me know if it works or if you're still stuck, and thus that perhaps the problem is still with FForms.

**Comment by magick93** [comment]
I think I will need the source code of Fresnel-Forms if I am to do what you recommend in the stackoverflow link.

**Comment by LloydRutledge** [comment]
The migration is a someday/maybe. There is an SVN for it at https://svnext.ou.nl/INF_Studenten_ABI_team30/source/ but that is read-only - not sure if you get more then what the download jar has.

**Comment by magick93** [comment]
I would encourage your give the migration a higher priority. You are more likely to get other developers to work on this, and then more users, if you migrate to github (or similar) soon.

This bug should serve as a good example. Its now not possible to use Fresnel forms in the latest release of Protege. And only those who have access to the source code can fix that - and who is that?

What, may I ask, are the problems/challenges to migrating?

**Comment by LloydRutledge** [comment]
You're right, I'll migrate soon, probably early next week. I thought the fix might be on your Protégé install, but with a new version compatibility bug we need the fix in FForms. Thanks for your advice.

**Comment by magick93** [comment]
Youre welcome.

I have watched your videos and read your presentations on Fresnel Forms. I'm really excited about this technology. I used to use SMW+ years ago, and really liked the integration with Owl. It looks like Fresnel Forms goes even further. So, Im sure I can find good value in it. And maybe I can help with the development of it.

**Comment by LloydRutledge** [comment]
I just put the src/ dir (and two others) in the code for this repository. Hopefully I've done it right so that you and others can access and work on it easily. Thanks for your interest! And if you can help with development that would be great!

**Comment by AlexMekkering** [comment]
Hi, great to get some feedback to our project!

I added the pom file from svn so FresnelForms could be built directly from git with Maven. It can also be imported in your IDE of choice (we used Eclipse).

FresnelForms has been tested with Protege versions until 5.0.0 beta 17, whilst the most recent version is now 5.0.0 beta 21. Simply changing maven dependencies to use 5.0.0 beta 21 doesn't work however, because the code's usage of the OWL API is incompatible with that of Protege. So, for now, the easiest way to get it working instantly is to install Protege version 5.0.0 beta 17 (https://github.com/protegeproject/protege/releases/tag/protege-parent-5.0.0-beta-17). In the meantime, I'm investigating this issue, but it might take some time to completely solve it.

Protege seems to have been adapted quite a lot recently, especially with respect to The OWL API, which was at version 3.5.1 when we tested FresnelForms and is now at version 4.1.3.
Locally, I adapted the code to be equivalent in functionality but use the new OWL API way of doing things. It now compiles, but deploying and testing still shows some problems. If useful, I could commit my changes for 5.0.0 beta 21 in a branch, but as I said, it isn't fit for use yet, I'll look into it more when I've some time left.

**Comment by magick93** [comment]
@AlexMekkering - thanks, yes it would be good if you can commit. And if you can also list the other problems, then we can address these too.
